{
    "unit_data": {
        "Product": "GNR",
        "Visual ID": "75779GB600065",
        "Bucket": "IDIPAR",
        "COM Port": "11",
        "IP Address": "10.250.0.2"
    },
    "experiments": [
        {
            "Experiment": "Enabled",
            "Test Name": "Baseline",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 2,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BootIssue",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 10,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 2,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BootIssue_vBCFC",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 20,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 2,
            "Type": "Voltage",
            "Domain": "CFC",
            "Start": 0.0,
            "End": 0.2,
            "Steps": 0.05,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BootIssue_vBIA",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 30,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 2,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": 0.0,
            "End": 0.2,
            "Steps": 0.05,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BootIssue_FlatCFC",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 40,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 2,
            "Type": "Frequency",
            "Domain": "CFC",
            "Start": 8.0,
            "End": 22.0,
            "Steps": 4.0,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BootIssue_FlatIA",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 50,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 2,
            "Type": "Frequency",
            "Domain": "IA",
            "Start": 8.0,
            "End": 32.0,
            "Steps": 4.0,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MaskChecks_CP1",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 101,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "FirstPass",
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MaskChecks_CP2",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 102,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "SecondPass",
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MaskChecks_CP3",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 103,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "ThirdPass",
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MaskChecks_RP1",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 201,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "RowPass1",
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MaskChecks_RP2",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 202,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "RowPass2",
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MaskChecks_RP3",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/boot_example.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 203,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "RowPass3",
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "FuseCollection",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "75779GB600065",
            "Bucket": "IDIPAR",
            "COM Port": 11,
            "IP Address": "10.250.0.2",
            "TTL Folder": "R:/Templates/GNR/version_1_0/TTL_Boot",
            "Scripts File": "R:/Templates/scripts/fuse_generation.txt",
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "PYSVConsole",
            "Test Number": 10,
            "Test Time": 30,
            "Reset": false,
            "Reset on PASS": false,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": "0xbf000000",
            "Disable 2 Cores": null,
            "Check Core": null,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 1,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": 0,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR50C_L_MOSBFT_HToff_pseudoSBFT_System\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Disable 1 Core": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Fuse File": null,
            "Bios File": null,
            "Product": "GNR"
        }
    ],
    "templates": {
        "0_Baseline": {
            "Experiment": "Enabled",
            "Test Name": "BaseRepro",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "R:\\Templates\\GNR\\version_2_0\\TTL_DragonMesh",
            "Scripts File": "C:\\SystemDebug\\ipc_powerdowns.txt",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Boot Breakpoint": "",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": "",
            "Voltage CFC": "",
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 2,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        },
        "1_IA_Voltage": {
            "Experiment": "Enabled",
            "Test Name": "IA_Voltage_check",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "R:\\Templates\\GNR\\version_2_0\\TTL_DragonMesh",
            "Scripts File": "C:\\SystemDebug\\ipc_powerdowns.txt",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Boot Breakpoint": "0xa2000000",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": "",
            "Voltage CFC": "",
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": 0.01,
            "End": 0.02,
            "Steps": 0.01,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        },
        "2_IA_Frequency": {
            "Experiment": "Enabled",
            "Test Name": "IA_Frequency_check",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "R:\\Templates\\GNR\\version_2_0\\TTL_DragonMesh",
            "Scripts File": "C:\\SystemDebug\\ipc_powerdowns.txt",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Boot Breakpoint": "0xa2000000",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": -0.03,
            "Voltage CFC": -0.03,
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 5,
            "Type": "Frequency",
            "Domain": "IA",
            "Start": 26,
            "End": 30,
            "Steps": 4,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        },
        "3_CFC_Voltage": {
            "Experiment": "Enabled",
            "Test Name": "CFC_Voltage_check",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "R:\\Templates\\GNR\\version_2_0\\TTL_DragonMesh",
            "Scripts File": "",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Boot Breakpoint": "0xa2000000",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": "",
            "Voltage CFC": "",
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "CFC",
            "Start": 0.01,
            "End": 0.02,
            "Steps": 0.01,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        },
        "4_CFC_Frequency": {
            "Experiment": "Enabled",
            "Test Name": "CFC_Frequency_check",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "R:\\Templates\\GNR\\version_2_0\\TTL_DragonMesh",
            "Scripts File": "C:\\SystemDebug\\ipc_powerdowns.txt",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Boot Breakpoint": "0xa2000000",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": "",
            "Voltage CFC": "",
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 5,
            "Type": "Frequency",
            "Domain": "CFC",
            "Start": 18,
            "End": 22,
            "Steps": 4,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        },
        "5_Shmoo_Core": {
            "Experiment": "Enabled",
            "Test Name": "Shmoo_Core_Volt_vs_Freq",
            "Test Mode": "Mesh",
            "Test Type": "Shmoo",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "R:\\Templates\\GNR\\version_2_0\\TTL_DragonMesh",
            "Scripts File": "C:\\SystemDebug\\ipc_powerdowns.txt",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Boot Breakpoint": "0xa2000000",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": "",
            "Voltage CFC": "",
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 3,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        },
        "6_Boot_Unit": {
            "Experiment": "Enabled",
            "Test Name": "Boot_Unit_check",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "EnterVisualID",
            "Bucket": "Framework",
            "COM Port": 8,
            "IP Address": "192.168.0.2",
            "TTL Folder": "C:\\SystemDebug\\TTL",
            "Scripts File": "C:\\SystemDebug\\ipc_powerdowns.txt",
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Boot Breakpoint": "0xa2000000",
            "Test Number": 1,
            "Test Time": 45,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": "",
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "",
            "Content": "PYSVConsole",
            "Disable 2 Cores": "",
            "Check Core": 0,
            "Voltage Type": "vbump",
            "Voltage IA": "",
            "Voltage CFC": "",
            "Frequency IA": "",
            "Frequency CFC": "",
            "Loops": 3,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX"
        }
    },
    "saved_date": "2026-02-17T16:45:49.314531",
    "tool": "PPV Experiment Builder v2.5",
    "file_type": "configuration"
}