{
    "unit_data": {
        "Product": "GNR",
        "Visual ID": "TemplateVID",
        "Bucket": "TemplateBucket",
        "COM Port": "11",
        "IP Address": "192.168.0.2"
    },
    "experiments": [
        {
            "Experiment": "Enabled",
            "Test Name": "Baseline",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BaselinePPVC",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "ppvc",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "BaselineXtended",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "ppvc",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x1C9C380",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "Slice_TSL_mini",
            "Test Mode": "Slice",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\\\RVP\\TTLs\\TTL_DragonSlice",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 1,
            "Test Time": 40,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": 36,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": null,
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc_mp1.xml --write_log_file_to_stdout=on --ituff=on",
            "Linux Content Line 1": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc_data_integrity.xml --write_log_file_to_stdout=on --ituff=on",
            "Linux Content Line 2": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc_data_integrity.xml --write_log_file_to_stdout=on --ituff=on",
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "CWF",
            "Product Chop": "CWF",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000002",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\GNR1C_Q_Slice_2M_pseudoSBFT_System",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "CFCVoltage",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "CFC",
            "Start": 0.05,
            "End": 0.2,
            "Steps": 0.05,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "CFCFrequency",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Frequency",
            "Domain": "CFC",
            "Start": 8.0,
            "End": 22.0,
            "Steps": 4.0,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "IAVoltage",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": 0.05,
            "End": 0.2,
            "Steps": 0.05,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "IAFrequencyLO",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Frequency",
            "Domain": "IA",
            "Start": 8.0,
            "End": 32.0,
            "Steps": 4.0,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "IAFrequencyHI",
            "Test Mode": "Mesh",
            "Test Type": "Sweep",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "S:\\GNR\\RVP\\TTLs\\TTL_DragonMesh",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Test Complete",
            "Fail String": "Test Failed",
            "Content": "Dragon",
            "Test Number": 11,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": false,
            "Core License": null,
            "600W Unit": false,
            "Pseudo Config": false,
            "Configuration (Mask)": "FirstPass",
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Frequency",
            "Domain": "IA",
            "Start": 36.0,
            "End": 40.0,
            "Steps": 4.0,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": null,
            "Linux Path": null,
            "Linux Content Wait Time": null,
            "Linux Content Line 0": null,
            "Linux Content Line 1": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL3s_Breadth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_breadth_HT.list -L 3000 -z U304_Breadth_3s.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL1s_Breadth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_breadth_HT.list -L 1000 -z U304_Breadth_1s.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL500ms_Breadth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_breadth_HT.list -L 500 -z U304_Breadth_500ms.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL100ms_Breadth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_breadth_HT.list -L 100 -z U304_Breadth_100ms.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL3s_BR",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_BR_HT.list -L 3000 -z U304_BR_3s.log -o -r10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL1s_BR",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_BR_HT.list -L 1000 -z U304_BR_1s.log -o -r10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL500s_BR",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_BR_HT.list -L 500 -z U304_BR_500ms.log -o -r10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL100ms_BR",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_BR_HT.list -L 100 -z U304_BR_100ms.log -o -r10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL3s_Depth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_depth_HT.list -L 3000 -z U304_depth_3s.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL1s_Depth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_depth_HT.list -L 1000 -z U304_depth_1s.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL500ms_Depth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_depth_HT.list -L 500 -z U304_depth_500ms.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "TSL100ms_Depth",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/TSL",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/tslengine -F /root/content/DPM/TSL/GNR1C_depth_HT.list -L 100 -z U304_depth_100ms.log -o -r 10",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "MLC",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "Result=SUCCESS",
            "Fail String": "Result=FAILED",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/MLC",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc.xml --write_log_file_to_stdout=on",
            "Linux Content Line 1": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc_data_integrity.xml --write_log_file_to_stdout=on",
            "Linux Content Line 2": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc_mp1.xml --write_log_file_to_stdout=on",
            "Linux Content Line 3": "/usr/local/bin/ocelot --flow /root/content/LOS/LOS-23WW24/Mlc/flows/Mlc_mp2.xml --write_log_file_to_stdout=on",
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Product": "GNR"
        },
        {
            "Experiment": "Enabled",
            "Test Name": "Sandstone",
            "Test Mode": "Mesh",
            "Test Type": "Loops",
            "Visual ID": "TemplateVID",
            "Bucket": "TemplateBucket",
            "COM Port": 11,
            "IP Address": "192.168.0.2",
            "TTL Folder": "Q:\\DPM_Debug\\GNR\\Logs\\3Strike\\759Q17J500189\\\\TTL_Linux",
            "Scripts File": null,
            "Post Process": null,
            "Pass String": "exit: pass",
            "Fail String": "exit: fail",
            "Content": "Linux",
            "Test Number": 9,
            "Test Time": 30,
            "Reset": true,
            "Reset on PASS": true,
            "FastBoot": true,
            "Core License": null,
            "600W Unit": true,
            "Pseudo Config": false,
            "Configuration (Mask)": null,
            "Boot Breakpoint": null,
            "Disable 2 Cores": null,
            "Check Core": 36,
            "Voltage Type": "vbump",
            "Voltage IA": null,
            "Voltage CFC": null,
            "Frequency IA": null,
            "Frequency CFC": null,
            "Loops": 5,
            "Type": "Voltage",
            "Domain": "IA",
            "Start": -0.03,
            "End": 0.06,
            "Steps": 0.03,
            "ShmooFile": "C:\\SystemDebug\\Shmoos\\RVPShmooConfig.json",
            "ShmooLabel": "COREFIX",
            "Linux Pre Command": null,
            "Linux Post Command": null,
            "Linux Pass String": null,
            "Linux Fail String": null,
            "Startup Linux": "startup_linux.nsh",
            "Linux Path": "cd /root/content/DPM/Sandstone",
            "Linux Content Wait Time": 999999,
            "Linux Content Line 0": "/root/content/LOS/TSL/bin/sandstone --max-test-loop-count=5 -t 200 -vv -o 0304_nominal_alltest.log",
            "Linux Content Line 1": null,
            "Linux Content Line 2": null,
            "Linux Content Line 3": null,
            "Dragon Pre Command": null,
            "Dragon Post Command": null,
            "Startup Dragon": "startup_efi.nsh",
            "ULX Path": "FS1:\\EFI\\ulx",
            "ULX CPU": "GNR_B0",
            "Product Chop": "GNR",
            "VVAR0": "0x4C4B40",
            "VVAR1": "80064000",
            "VVAR2": "0x1000000",
            "VVAR3": "0x4000000",
            "VVAR_EXTRA": null,
            "Dragon Content Path": "FS1:\\content\\Dragon\\7410_0x0E_PPV_MegaMem\\GNR128C_H_1UP\\",
            "Dragon Content Line": null,
            "Stop on Fail": true,
            "Merlin Name": "MerlinX.efi",
            "Merlin Drive": "FS1:",
            "Merlin Path": "FS1:\\EFI\\Version8.15\\BinFiles\\Release",
            "Fuse File": null,
            "Bios File": null,
            "Disable 1 Core": null,
            "Linux Content Line 4": null,
            "Linux Content Line 5": null,
            "Linux Content Line 6": null,
            "Linux Content Line 7": null,
            "Linux Content Line 8": null,
            "Linux Content Line 9": null,
            "Product": "GNR"
        }
    ],
    "templates": {},
    "saved_date": "2026-02-19T16:24:28.319502",
    "tool": "PPV Experiment Builder v2.5",
    "file_type": "configuration"
}